package carmine.compiler.structures;

public enum TokenType
{
    LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE,
    ENDLINE,
    COMMA, SEMICOLON, DOT,
    PLUS, MINUS,
    MUL, DIV, MOD, EXP,
    AND, OR, NOT,
    EQUAL, NOTEQUAL, LESS, GREATER, GREATER_EQUAL, LESS_EQUAL,
    ASSIGN,
    IF, ELSE, WHILE, FOR,
    IDENTIFIER, BINARY, DECIMAL, HEXADECIMAL, TRUE, FALSE, NULL,
    ENUM,
    ARROW, //WIRE, INPUT,
    MODULE, VAR,
    ERR,
    EOF
}
